language: ruby
rvm:
  - 2.6.3

# currenlt only testing on docs via Rakefile 
script:
  - bundle exec rake html_proofer

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch
  - update-maven-docs # docs update branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: 
  bundler: true # caching bundler gem packages will speed up build
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false